// <auto-generated />
using DSED_07_Web_Development.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DSED_07_Web_Development.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20190222061032_LatestCreate")]
    partial class LatestCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DSED_07_Web_Development.Models.ComuterScience", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnName("BookID");

                    b.Property<string>("BookAuthor")
                        .HasMaxLength(50);

                    b.Property<string>("BookName")
                        .HasMaxLength(50);

                    b.Property<double?>("BookPrice");

                    b.HasKey("BookId");

                    b.ToTable("ComuterScience");
                });

            modelBuilder.Entity("DSED_07_Web_Development.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId");

                    b.Property<string>("Age")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Mobile")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DSED_07_Web_Development.Models.Novels", b =>
                {
                    b.Property<int>("NovelId")
                        .HasColumnName("NovelID");

                    b.Property<string>("NovelAuthor")
                        .HasMaxLength(50);

                    b.Property<string>("NovelName")
                        .HasMaxLength(50);

                    b.Property<double?>("NovelPrice");

                    b.HasKey("NovelId");

                    b.ToTable("Novels");
                });

            modelBuilder.Entity("DSED_07_Web_Development.Models.Sports", b =>
                {
                    b.Property<int>("SportId");

                    b.Property<string>("SportCoach")
                        .HasMaxLength(50);

                    b.Property<double?>("SportFees");

                    b.Property<string>("SportName")
                        .HasMaxLength(50);

                    b.HasKey("SportId");

                    b.ToTable("Sports");
                });
#pragma warning restore 612, 618
        }
    }
}
